triggers:
- id: ff7e1336
  name: Pete
  type: send_sticker
  matcher: image_similarity
  chance: 1.0
  params:
    pattern: triggers/repete_4fe7.jpg
    hash: e0f7fac12e18259c
  files:
  - assets/pete_4a31.jpg
- id: 754781a0
  name: Repete
  type: send_sticker
  matcher: image_similarity
  chance: 1.0
  params:
    pattern: triggers/pete_1c83.jpg
    hash: 95cb3b14c564b56a
  files:
  - assets/repete_86a8.jpg
- id: 6f996520
  name: Repete2
  type: send_sticker
  matcher: text
  chance: 1.0
  params:
    pattern: repete
  files:
  - assets/pete_21d8.jpg
- id: f0d02ff9
  name: De Quem
  type: send_contact
  matcher: text
  chance: 1.0
  params:
    pattern: de quem Ã©
  action: meme_contact
- id: cd793f48
  name: De Quem 2
  type: send_contact
  matcher: text
  chance: 1.0
  params:
    pattern: de quem e
  action: meme_contact
- id: e64d6e9d
  name: Padim zeras
  type: send_sticker
  matcher: text
  chance: 1.0
  params:
    pattern: padim zeras
  files:
  - assets/padim_zeras_3_3f36.webp
  - assets/padim_zeras_1_14a7.webp
  - assets/padim_zeras_2_362f.webp
- id: ac260faf
  name: Contexto
  type: send_sticker
  matcher: text
  chance: 1.0
  params:
    pattern: contexto
  files:
  - assets/contexto_2106.webp
- id: f89cda37
  name: Pete2
  type: send_sticker
  matcher: text
  chance: 1.0
  params:
    pattern: eu tenho dois cachorros pete e repete pete sumiu quem sobrou
  files:
  - assets/repete_cda6.jpg
- id: b7828203
  name: mylib
  type: send_text
  matcher: text
  chance: 1.0
  params:
    pattern: mylib
  value: https://master.dple1clh7kw1l.amplifyapp.com
- id: cdf60b40
  name: mylib2
  type: send_text
  matcher: text
  chance: 1.0
  params:
    pattern: my_lib
  value: https://master.dple1clh7kw1l.amplifyapp.com
- id: 45d10842
  name: natal
  type: send_text
  matcher: text
  chance: 0.8
  params:
    pattern: natal
  value: ''
  files:
  - assets/natal_a1a0.txt
- id: f31e70f7
  name: fred
  type: send_text
  matcher: text
  chance: 0.8
  params:
    pattern: fred
  value: ''
  files:
  - assets/pokemon_398e.txt
- id: 74d9e3e5
  name: bom dia
  type: send_text
  matcher: text
  chance: 1.0
  params:
    pattern: bom dia
  value: ''
  files:
  - assets/bom_dia_fdcf.json
- id: 0e2c8615
  name: trabalho
  type: send_text
  matcher: text
  chance: 0.8
  params:
    pattern: trabalho
  value: ''
  files:
  - assets/coach_f3af.txt
- id: b498bf09
  name: burro
  type: send_text
  matcher: text
  chance: 0.8
  params:
    pattern: burro
  value: ''
  files:
  - assets/intelectual_4806.txt
- id: 3af8935d
  name: jogo
  type: send_text
  matcher: text
  chance: 0.8
  params:
    pattern: jogo
  value: ''
  files:
  - assets/gamer_fda6.txt
- id: f4cea95e
  name: voar
  type: send_text
  matcher: text
  chance: 0.8
  params:
    pattern: voar
  value: ''
  files:
  - assets/abelha_3a8e.txt
- id: 3c7aef81
  name: comida
  type: send_text
  matcher: text
  chance: 0.8
  params:
    pattern: comida
  value: ''
  files:
  - assets/comida_56fc.txt
- id: '63953704'
  name: tempo
  type: send_text
  matcher: text
  chance: 0.8
  params:
    pattern: tempo
  value: ''
  files:
  - assets/fisica_a301.txt
- id: 1a3e066a
  name: aniversÃ¡rio
  type: send_audio
  matcher: regex
  chance: 0.1
  params:
    pattern: (aniversÃ¡rio|aniversario|birthday)
  files:
  - assets/parabens_686c.mp3
- id: d08402c7
  name: sextou
  type: send_audio
  matcher: text
  chance: 1.0
  params:
    pattern: sextou
  files:
  - assets/sextou_671b.mp3
- id: 69bd2b24
  name: gato1
  type: send_text
  matcher: text
  chance: 0.2
  params:
    pattern: gat
  action: cat_api
- id: b9c65eac
  name: gato2
  type: send_sticker
  matcher: text
  chance: 1.0
  params:
    pattern: gato
  action: cat_photo_api
- id: 5ab79aaa
  name: motivacional
  type: send_text
  matcher: regex
  chance: 0.8
  params:
    pattern: (sucesso|vencer|conseguir)
  action: motivacional
- id: 1bdd8aef
  name: chuck norries
  type: send_text
  matcher: regex
  chance: 1.0
  params:
    pattern: (chuck|norris)
  action: chuck_norris
- id: c78373fa
  name: cachorro
  type: send_sticker
  matcher: regex
  chance: 1.0
  params:
    pattern: (cachorro|dog)
  action: dog_api
- id: b47f0891
  name: idiota
  type: send_sticker
  matcher: regex
  chance: 1.0
  params:
    pattern: (idiota|bonk)
  action: bonk
- id: 71cd9a45
  name: feliz
  type: send_sticker
  matcher: text
  chance: 0.5
  params:
    pattern: feliz
  action: smile
- id: 4680de2d
  name: conselho
  type: send_text
  matcher: regex
  chance: 1.0
  params:
    pattern: (conselho|recomendaÃ§Ã£o)
  action: advice
- id: 5d7bce20
  name: anime
  type: send_text
  matcher: text
  chance: 0.5
  params:
    pattern: anime
  action: anime_quote
no_triggers:
- id: 0e48ec71
  name: BreakingBad
  type: send_text
  matcher: always
  chance: 0.01
  params:
    pattern: ''
  action: breaking_bad
- id: e4ff96cc
  name: Observando
  type: send_text
  matcher: always
  chance: 0.001
  params:
    pattern: ''
  value: Estou te observando... ðŸ‘€
