triggers:
- id: '69238301'
  name: Pete
  type: send_sticker
  matcher: image_similarity
  chance: 1.0
  params:
    pattern: triggers/repete_4fe7.jpg
    hash: e0f7fac12e18259c
  files:
  - assets/pete_4a31.jpg
- id: 37bbb554
  name: Repete
  type: send_sticker
  matcher: image_similarity
  chance: 1.0
  params:
    pattern: triggers/pete_1c83.jpg
    hash: 95cb3b14c564b56a
  files:
  - assets/repete_86a8.jpg
- id: 94449fc5
  name: Repete2
  type: send_sticker
  matcher: text
  chance: 1.0
  params:
    pattern: repete
  files:
  - assets/pete_21d8.jpg
- id: e7d236a0
  name: De Quem
  type: send_contact
  matcher: text
  chance: 1.0
  params:
    pattern: de quem Ã©
  action: meme_contact
- id: '50079009'
  name: De Quem 2
  type: send_contact
  matcher: text
  chance: 1.0
  params:
    pattern: de quem e
  action: meme_contact
- id: bfd817a0
  name: Padim zeras
  type: send_sticker
  matcher: text
  chance: 1.0
  params:
    pattern: padim zeras
  files:
  - assets/padim_zeras_3_3f36.webp
  - assets/padim_zeras_1_14a7.webp
  - assets/padim_zeras_2_362f.webp
- id: bc6e452f
  name: Contexto
  type: send_sticker
  matcher: text
  chance: 1.0
  params:
    pattern: contexto
  files:
  - assets/contexto_2106.webp
- id: e416243a
  name: Pete2
  type: send_sticker
  matcher: text
  chance: 1.0
  params:
    pattern: eu tenho dois cachorros pete e repete pete sumiu quem sobrou
  files:
  - assets/repete_cda6.jpg
- id: f288101b
  name: mylib
  type: send_text
  matcher: text
  chance: 1.0
  params:
    pattern: mylib
  value: https://master.dple1clh7kw1l.amplifyapp.com
- id: d3d45f79
  name: mylib2
  type: send_text
  matcher: text
  chance: 1.0
  params:
    pattern: my_lib
  value: https://master.dple1clh7kw1l.amplifyapp.com
- id: 237b8c34
  name: natal
  type: send_text
  matcher: text
  chance: 0.8
  params:
    pattern: natal
  value: ''
  files:
  - assets/natal_a1a0.txt
- id: 164bc752
  name: fred
  type: send_text
  matcher: text
  chance: 0.8
  params:
    pattern: fred
  value: ''
  files:
  - assets/pokemon_398e.txt
- id: b421ba3c
  name: bom dia
  type: send_text
  matcher: text
  chance: 1.0
  params:
    pattern: bom dia
  value: ''
  files:
  - assets/bom_dia_fdcf.json
- id: 5797ac9a
  name: trabalho
  type: send_text
  matcher: text
  chance: 0.8
  params:
    pattern: trabalho
  value: ''
  files:
  - assets/coach_f3af.txt
- id: 2b575ca5
  name: burro
  type: send_text
  matcher: text
  chance: 0.8
  params:
    pattern: burro
  value: ''
  files:
  - assets/intelectual_4806.txt
- id: bd698fc4
  name: jogo
  type: send_text
  matcher: text
  chance: 0.8
  params:
    pattern: jogo
  value: ''
  files:
  - assets/gamer_fda6.txt
- id: 47d26b18
  name: voar
  type: send_text
  matcher: text
  chance: 0.8
  params:
    pattern: voar
  value: ''
  files:
  - assets/abelha_3a8e.txt
- id: 196725d3
  name: comida
  type: send_text
  matcher: text
  chance: 0.8
  params:
    pattern: comida
  value: ''
  files:
  - assets/comida_56fc.txt
- id: e9dc6b15
  name: tempo
  type: send_text
  matcher: text
  chance: 0.8
  params:
    pattern: tempo
  value: ''
  files:
  - assets/fisica_a301.txt
- id: 98ff09d4
  name: aniversÃ¡rio
  type: send_audio
  matcher: regex
  chance: 0.1
  params:
    pattern: (aniversÃ¡rio|aniversario|birthday)
  files:
  - assets/parabens_686c.mp3
- id: 7a4fe60d
  name: sextou
  type: send_audio
  matcher: text
  chance: 1.0
  params:
    pattern: sextou
  files:
  - assets/sextou_671b.mp3
- id: a7a42a10
  name: gato1
  type: send_text
  matcher: text
  chance: 0.2
  params:
    pattern: gat
  action: cat_api
- id: 2173d94c
  name: gato2
  type: send_sticker
  matcher: text
  chance: 1.0
  params:
    pattern: gato
  action: cat_photo_api
- id: 0d9ac78f
  name: motivacional
  type: send_text
  matcher: regex
  chance: 0.8
  params:
    pattern: (sucesso|vencer|conseguir)
  action: motivacional
- id: e10a82ad
  name: chuck norries
  type: send_text
  matcher: regex
  chance: 1.0
  params:
    pattern: (chuck|norris)
  action: chuck_norris
- id: 659f7b59
  name: cachorro
  type: send_sticker
  matcher: regex
  chance: 1.0
  params:
    pattern: (cachorro|dog)
  action: dog_api
- id: 7de5f1a2
  name: idiota
  type: send_sticker
  matcher: regex
  chance: 1.0
  params:
    pattern: (idiota|bonk)
  action: bonk
- id: 8cb1b69b
  name: feliz
  type: send_sticker
  matcher: text
  chance: 0.5
  params:
    pattern: feliz
  action: smile
- id: 0f5dac72
  name: conselho
  type: send_text
  matcher: regex
  chance: 1.0
  params:
    pattern: (conselho|recomendaÃ§Ã£o)
  action: advice
- id: eda4c020
  name: anime
  type: send_text
  matcher: text
  chance: 0.5
  params:
    pattern: anime
  action: anime_quote
no_triggers:
- id: 7eb25ab8
  name: BreakingBad
  type: send_text
  matcher: always
  chance: 0.01
  params:
    pattern: ''
  action: breaking_bad
- id: 63aefab4
  name: Observando
  type: send_text
  matcher: always
  chance: 0.001
  params:
    pattern: ''
  value: Estou te observando... ðŸ‘€
